version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    # command: go run main.go -b 0.0.0.0
    command: air ./main.go -b 0.0.0.0
    depends_on: 
      - redis

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"
